# Generated by Django 5.1.3 on 2024-11-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'Reports'},
        ),
        migrations.AddField(
            model_name='report',
            name='report_description',
            field=models.CharField(default='placeholder description', max_length=200),
            preserve_default=False,
        ),
    ]
