# Generated by Django 5.1.3 on 2024-11-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_alter_report_options_report_report_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', help_text='Upload an image of the issue', upload_to=''),
        ),
    ]
